FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App
# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore --disable-parallel
# Build and publish a release
RUN dotnet publish -c Release

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App

ENV ASPNETCORE_URLS=http://0.0.0.0:5180
COPY --from=build-env /App/bin/Release/net8.0/ .
ENTRYPOINT ["dotnet", "capstone.dll"]